name: wf-dev-lint
on: 
  pull_request:
    branches:
      - develop
jobs:
  lint-buid-job:
    runs-on: ubuntu-latest
    steps :
      - name : repo checkout
        uses: actions/checkout@v4
      - name : Lint Html and Css files
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Try build 
        run: |
          npx parcel build ".src/index.html" --dist-dir "./dev" --public-url "./"